FROM debian:bullseye

ENV DEBIAN_FRONTEND=noninteactive

RUN apt-get update && apt-get install -y  \
	build-essential valgrind zsh curl ca-certificates procps \
	netcat-openbsd libc6-dbg gdb make\
	&& rm -rf var/lib/apt/lists/*

WORKDIR /app
