services:
  dev:
    container_name: webserv-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: webserv-dev
    command: zsh
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
     - "8080:8080"
